# Generated by Django 5.2.7 on 2025-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='final_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
